### ISSUE TITLE
「Access to undeclared static property」エラーが表示される

### ISSUE THREAD

**Issue by webbingstudio** [PowerCMS/DynamicMTML#7]
こんにちは。DynamicMTMLを利用しているサイトのMovable Typeを6.0.3 -> 6.3.6にバージョンアップしたところ、ページが表示されなくなりました。

以下の通り、static宣言がされてないためアクセス出来ない旨のエラーが返っています。
PHP5.6系、PHP7両方で確認しております。

```
Notice:
Error: Access to undeclared static property: MT::$config_type_hash

#0 /path/to/mt/addons/DynamicMTML.pack/php/mt.php(363): Config->data()
#1 /path/to/mt/addons/DynamicMTML.pack/php/mt.php(124): MT->configure_from_db()
#2 /path/to/mt/addons/DynamicMTML.pack/php/mt.php(78): MT->init(5, '/path/to...')
#3 /path/to/mt/addons/DynamicMTML.pack/php/mt.php(86): MT->__construct(5, '/path/to...')
#4 /path/to/mt/addons/DynamicMTML.pack/php/dynamicmtml.run.php(200): MT::get_instance(5, '/path/to...')
#5 /path/to/member/.mtview.php(31): require_once('/path/to...')
#6 {main}
in /path/to/mt/php/lib/class.exception.php on line 97
```

Movable Typeのコア側の変更に関わるものでしょうか。
宜しくお願いいたします。

**Comment by alfasado** [comment]
@webbingstudio お問い合わせ頂きました件、ご利用の DynamicMTML のバージョンはいくつでしょうか。
Movable Type 6.3 でダイナミックパブリッシングまわりで大きな仕様変更があり、それに対応するため MT6.3 以上に向けた DynamicMTML 3.0 を新しくリリースしております。

https://github.com/PowerCMS/DynamicMTML3.0

ご利用の DynamicMTML が 3.0 でない場合、DynamicMTML 3.0 へ入れかえて動作をご確認頂けますか。

よろしくお願いします。

**Comment by webbingstudio** [comment]
ありがとうございます！
DynamicMTML 3.0に入れ替えたところ、PHPのエラーはなくなったのですが、DynamicMTMLのタグを解釈しなくなってしまいました。
addonディレクトリ内のコアファイルを入れ替えてから、テンプレート画面でDynamicMTML .htaccessと、DynamicMTML Bootstrapperを再生成すればよいと思ったのですが…

設定をいちから見直してみたいと思います。
動作環境はエックスサーバーで、Movable Type Pro version 6.3.6＋PHP7です。

なお、エックスサーバーは、DynamicMTMLが自動生成する.htaccessのうち、以下をサポートしておらず500エラーとなります。
前のバージョンではコメントアウトすれば問題なく動作しました。

```
php_flag short_open_tag off
```
